version: '3.8'
services:

    elasticsearch:
        image: elasticsearch:$ELASTIC_VERSION
        container_name: elasticsearch
        restart: unless-stopped
        ports:
            - $ELASTIC_PORT:9200
        volumes:
            - ./elasticsearch-data:/usr/share/elasticsearch/data
            - ./elasticsearch-logs:/usr/share/elasticsearch/logs
        networks:
            - elastic

    kibana:
        image: kibana:$KIBANA_VERSION
        container_name: kibana
        restart: unless-stopped
        environment:
            - ELASTICSEARCH_HOSTS=$ELASTIC_HOSTNAME
        ports:
            - $KIBANA_PORT:5601
        links: 
            - elasticsearch
        depends_on: 
            - elasticsearch
        networks:
            - elastic

    filebeat:
        image: docker.elastic.co/beats/filebeat:$FIREBEAT_VERSION
        container_name: filebeat
        command: >
            bash -c ''
        volumes:
            - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
            - ./test.log:/var/log/app_logs/test.log
            - data-firebeat:/usr/share/elasticsearch/config/certs
        depends_on: 
            - elasticsearch
        links: 
            - elasticsearch
        networks:
            - elastic

volumes:
    elasticsearch-data:
    elasticsearch-logs:
    data-firebeat:

networks:
  elastic:
    name: elastic